### ISSUE TITLE
[PRE REVIEW]: Developing and deploying an integrated workshop curriculum teaching computational skills for reproducible research

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#116]
**Submitting author:** @pschloss (<a href="http://orcid.org/0000-0002-6935-4275">Patrick D Schloss</a>)
**Repository:** <a href="https://github.com/UMCarpentries/intro-curriculum-r/tree/gh-pages/paper" target ="_blank">https://github.com/UMCarpentries/intro-curriculum-r/tree/gh-pages/paper</a>
**Version:** v0.1.0
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Lorena Barba

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://jose.theoj.org/papers/4649d22db51c8150274f83f806792dc9/status.svg)](https://jose.theoj.org/papers/4649d22db51c8150274f83f806792dc9)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/4649d22db51c8150274f83f806792dc9"><img src="https://jose.theoj.org/papers/4649d22db51c8150274f83f806792dc9/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/4649d22db51c8150274f83f806792dc9/status.svg)](https://jose.theoj.org/papers/4649d22db51c8150274f83f806792dc9)
```

**Author instructions**

Thanks for submitting your paper to JOSE @pschloss. **Currently, there isn't an JOSE editor assigned** to your paper.

@pschloss if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #116 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by pschloss** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #116 with the following error: 
```
 ORCID looks to be the wrong length
/app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `block in check_orcids': Problem with ORCID (0000-0001-7074-401) for Catherine Barnier (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by pschloss** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #116 with the following error: 
```
 ORCID looks to be the wrong length
/app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:155:in `block in check_orcids': Problem with ORCID (0000-0002-8249-1186 ) for Maya M. Lapp (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:153:in `check_orcids'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon.rb:90:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-92346a0773a4/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by pschloss** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00116/jose.00116/10.21105.jose.00116.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00116/jose.00116/10.21105.jose.00116.pdf) :page_facing_up: :point_left:

**Comment by pschloss** [comment]
Possible reviewers. All suggested because of their prior interactions with the Carpentries and commitment to open science education...

* Tracy Teal
* Kim Dill-McFarland
* Kate Hertweck

**Comment by magsol** [comment]
Hi @pschloss, thanks for your patience and sorry for the delay. I was looking into tickets that could use a nudge and have sent out review invitations to Drs. Dill-McFarland and Hertweck (thank you for the names). I couldn't find contact information for Tracy Teal. Do you have this information?

**Comment by magsol** [comment]
@whedon add me as editor

**Comment by whedon** [comment]
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by magsol** [comment]
@whedon assign me as editor

**Comment by whedon** [comment]
OK, the editor is @magsol

**Comment by pschloss** [comment]
Her GitHub handle is tracykteal

Pat

**Comment by magsol** [comment]
@whedon assign @kdillmcfarland as reviewer

**Comment by whedon** [comment]
OK, @kdillmcfarland is now a reviewer

**Comment by magsol** [comment]
@tracykteal Hi Tracy 👋 — would you consider contributing a peer review for JOSE? (The Journal of Open Source Education)
Submission title: "**Developing and deploying an integrated workshop curriculum teaching computational skills for reproducible research**"

**Comment by pschloss** [comment]
Hey @magsol  - curious if we can do anything to help identify a second reviewer?
