### ISSUE TITLE
[PRE REVIEW]: Check your outliers! An introduction to identifying statistical outliers in R with *easystats*

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#211]
**Submitting author:** @rempsyc (<a href="http://orcid.org/0000-0003-4315-6788">Rémi Thériault</a>)
**Repository:** https://github.com/easystats/performance
**Branch with paper.md** (empty if default branch): JOSE_paper
**Version:** 
**Editor:** @stats-tgeorge
**Reviewers:** @nniiicc, @lebebr01
**Managing EiC:** Lorena Barba

 

## Status

[![status](https://jose.theoj.org/papers/42749638170253bb2854649fb52bf4ca/status.svg)](https://jose.theoj.org/papers/42749638170253bb2854649fb52bf4ca)

Status badge code:

```
HTML: <a href="https://jose.theoj.org/papers/42749638170253bb2854649fb52bf4ca"><img src="https://jose.theoj.org/papers/42749638170253bb2854649fb52bf4ca/status.svg"></a>
Markdown: [![status](https://jose.theoj.org/papers/42749638170253bb2854649fb52bf4ca/status.svg)](https://jose.theoj.org/papers/42749638170253bb2854649fb52bf4ca)
```

**Author instructions**

Thanks for submitting your paper to JOSE @rempsyc. **Currently, there isn't an JOSE editor assigned** to your paper.

@rempsyc if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSE reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSE is currently operating in a "reduced service mode". 

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Wordcount for `paper.md` is 1763

**Comment by whedon** [comment]
PDF failed to compile for issue #211 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `initialize': No such file or directory @ rb_sysopen - fbb16f1ba25927691ad4e2df/papers/Mathematics/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:66:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.27 s (707.6 files/s, 104566.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                              147           3078           5136          11223
TeX                              7            462            214           3641
XML                              1              0             42           1484
Markdown                        11            547              0           1208
Rmd                              6            367            641            318
YAML                            22             50             45            211
-------------------------------------------------------------------------------
SUM:                           194           4504           6078          18085
-------------------------------------------------------------------------------


Statistical information for the repository 'bfcb14137a926679f9dc7f0e' was
gathered on 2023/06/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Daniel                           4           176            376           73.40
Dominique Makowski               1           200              0           26.60

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
```

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.21105/joss.01541 is OK
- 10.21105/joss.01412 is OK
- 10.5281/zenodo.3952153 is OK
- 10.5281/zenodo.3952214 is OK
- 10.1111/2041-210X.12225 is OK
- 10.21105/joss.02445 is OK
- 10.21105/joss.02306 is OK
- 10.1098/rsif.2017.0213 is OK
- 10.2307/1912557 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by rempsyc** [comment]
Hi, as explained in the cover letter, the correct `.md` file is in the "JOSE_paper" branch (https://github.com/easystats/performance/tree/JOSE_paper). The submission form did not accept the branch URL and there was no box for specifying a branch. Is there a way to ask whedon to change the target repository? Thanks

**Comment by rempsyc** [comment]
@whedon generate pdf from branch JOSE_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSE_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #211 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: tags, date (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by rempsyc** [comment]
@whedon generate pdf from branch JOSE_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSE_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #211 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:147:in `check_fields': Paper YAML header is missing expected fields: tags, date (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:89:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by rempsyc** [comment]
@whedon generate pdf from branch JOSE_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSE_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #211 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Rémi Thériault, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by rempsyc** [comment]
@whedon generate pdf from branch JOSE_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSE_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00211/jose.00211/10.21105.jose.00211.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00211/jose.00211/10.21105.jose.00211.pdf) :page_facing_up: :point_left:

**Comment by rempsyc** [comment]
For potential reviewers, we would suggest authors of key cited papers in the current manuscript (including an expert statistician):
- Daniël Lakens (Lakens)
- Marie Delacre (mdelacre)
- Youri L. Mora (YouriLMora)

Else from the suggested list: 
- mdogucu
- johnlray
- lebebr01
- nniiicc
- kbodwin

**Comment by stats-tgeorge** [comment]
@whedon assign @stats-tgeorge as editor

**Comment by whedon** [comment]
OK, the editor is @stats-tgeorge

**Comment by stats-tgeorge** [comment]
Hello @rempsyc I am excited to start the review process of your submission! I looked over your materials and found a few items to get resolved before I invite reviews. See opened **issue 594** on your JOSE branch of the repository.

**Comment by rempsyc** [comment]
@whedon generate pdf from branch JOSE_paper

**Comment by whedon** [comment]
```
Attempting PDF compilation from custom branch JOSE_paper. Reticulating splines etc...
```

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00211/jose.00211/10.21105.jose.00211.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/jose-papers/blob/jose.00211/jose.00211/10.21105.jose.00211.pdf) :page_facing_up: :point_left:

**Comment by xuanxu** [comment]
@editorialbot set JOSE_paper as branch

**Comment by stats-tgeorge** [comment]
@whedon list reviewers

**Comment by stats-tgeorge** [comment]
@editorialbot list reviewers

**Comment by stats-tgeorge** [comment]
Hello @lebebr01. I hope you are having a great summer! Would you be willing to review this JOSE submission?

**Comment by stats-tgeorge** [comment]
Hello @mdogucu. I hope you are having a great summer! Would you be willing to review this JOSE submission?

**Comment by stats-tgeorge** [comment]
Hello @trallard. I hope you are having a great summer! Would you be willing to review this JOSE submission?

**Comment by mdogucu** [comment]
> Hello @mdogucu. I hope you are having a great summer! Would you be willing to review this JOSE submission?

I am unable to review it at the moment @stats-tgeorge. Sorry about that.

**Comment by stats-tgeorge** [comment]
Hello @kbodwin. I hope you are having a great summer! Would you be willing to review this JOSE submission?

**Comment by stats-tgeorge** [comment]
Hello @nniiicc. I hope you are having a great summer! Would you be willing to review this JOSE submission?

**Comment by nniiicc** [comment]
@stats-tgeorge happy to

**Comment by stats-tgeorge** [comment]
@nniiicc  thank you so much. I need to find 1 more reviewer and then you all can get started. I hope the delay has not decreased your willingness!

**Comment by stats-tgeorge** [comment]
Hello @johnlray. I hope you are having a great summer! Would you be willing to review this JOSE submission?

**Comment by stats-tgeorge** [comment]
Hello @jhollist. I hope you are having a great summer! Would you be willing to review this JOSE submission?

**Comment by lebebr01** [comment]
@stats-tgeorge, getting back to this; I should be able to do this sometime in early to mid August.

**Comment by nniiicc** [comment]
@stats-tgeorge I think if you use `@editorialbot add @nniiicc @lebebr01 as reviewers` we should be ready to start. Thanks!

**Comment by stats-tgeorge** [comment]
@editorialbot assign @nniiicc as reviewer

**Comment by stats-tgeorge** [comment]
@editorialbot  commands

**Comment by stats-tgeorge** [comment]
@editorialbot commands

**Comment by stats-tgeorge** [comment]
@editorialbot assign @nniiicc as reviewer

**Comment by stats-tgeorge** [comment]
@editorialbot add @nniiicc as reviewer

**Comment by stats-tgeorge** [comment]
@editorialbot add @lebebr01 to reviewers

**Comment by stats-tgeorge** [comment]
@lebebr01  and @nniiicc  thank you very much for agreeing to review! I am starting the review version now!

**Comment by stats-tgeorge** [comment]
@editorialbot start review
