### ISSUE TITLE
[PRE REVIEW]: Quantitative Big Imaging

### ISSUE THREAD

**Issue by whedon** [openjournals/jose-reviews#22]
**Submitting author:** @kmader (<a href="http://orcid.org/0000-0003-4919-9359">Kevin Mader</a>)
**Repository:** <a href="https://github.com/kmader/Quantitative-Big-Imaging-2018/tree/jose-submission" target ="_blank">https://github.com/kmader/Quantitative-Big-Imaging-2018/tree/jose-submission</a>
**Version:** v2018
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSE @kmader. The JOSE editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@kmader if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/jose-reviewers) have already agreed to review for JOSE and may be suitable for this submission.

**Editor instructions**

The JOSE submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #22 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by labarba** [comment]
@kmader : I believe you've got the metadata section of the paper wrong. See this published paper, as an example:
https://raw.githubusercontent.com/arm61/pylj/master/paper/paper.md

**Comment by kmader** [comment]
hmm, I tried to copy as closely as possible: https://raw.githubusercontent.com/kmader/Quantitative-Big-Imaging-2018/jose-submission/paper.md
I can't seem to figure out from the ruby messages what is going on, is it because it isn't the master branch?

**Comment by labarba** [comment]
I actually don't know the answer to your question. I know that the directory location does not matter, as `whedon` looks for the `paper.md` file wherever it may be. But I don't know if it works on a branch! That's a question for @arfon, but he's on vacation until 22 July.

**Comment by labarba** [comment]
On the other hand, it doesn't seem like a good idea to give us a URL to a branch in the "Submission repository," as this carries over to the Review issue and than to the published paper's page on the journal. 😬

**Comment by kyleniemeyer** [comment]
I do think the paper needs to be in master, though I'm not 100% sure.

**Comment by kmader** [comment]
Can I change it or do I need to delete and resubmit? I was hoping to keep the JOSE part off the master branch until it was finalized but it's not a problem.

**Comment by labarba** [comment]
If you merge it to master, I can manually edit this issue and try to recompile, to see if it works!

**Comment by kyleniemeyer** [comment]
You can just change it, then prompt a new attempt to compile with `@whedon generate pdf`

**Comment by kmader** [comment]
So it's merged now
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #22 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `block in find': No such file or directory (Errno::ENOENT)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:32:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by labarba** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/jose-papers/blob/jose.00022/jose.00022/10.21105.jose.00022.pdf)

**Comment by arfon** [comment]
> I do think the paper needs to be in master, though I'm not 100% sure.

👍 the paper needs to be in the default Git branch which for the vast majority of repositories is `master`.

**Comment by labarba** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by katyhuff** [comment]
@whedon assign @katyhuff as editor

**Comment by whedon** [comment]
OK, the editor is @katyhuff

**Comment by katyhuff** [comment]
Hi folks. I can handle editing this but it will be a few days before I will be able to give it my full attention. Thank you in advance for your patience.

**Comment by katyhuff** [comment]
@arokem and @ThomasA: I think you would both be excellent reviewers for [this JOSE submission](https://github.com/openjournals/jose-papers/blob/jose.00022/jose.00022/10.21105.jose.00022.pdf) regarding Quantitative Big Imaging.

The Journal of Open Source Education Reviewer Guidelines can be found [here](http://jose.theoj.org/about#reviewer_guidelines), and are very similar to the guidelines for JOSS. Please note that JOSE accepts two types of submissions: (1) computational learning modules, created as open educational resources (OER), and (2) open-source software, created as educational technology or infrastructure. This one appears to be a submission of the first type.


What do you think: would you be willing to review this submission to JOSE?

**Comment by arokem** [comment]
Yeah. Sign me up!

**Comment by ThomasA** [comment]
It sounds good. I would like to review. I just have one review in the pipeline for JORS that I need to finish first.
